#!/bin/sh

# Copyright (c) 2021, C. Tarbide.
# All rights reserved.

# Permission to distribute and use this work for any
# purpose is hereby granted provided this copyright
# notice is included in the copy.  This work is provided
# as is, with no warranty of any kind.

# objective: use a posix shell (dash, mksh) and awk
# (nawk, mawk) to generate a portable Makefile

set -eu

die(){ ev=$1; shift; for msg in "$@"; do echo "${msg}"; done; exit "${ev}"; }

thisdir=${0%/*}

BUILD_AWK=${AWK:-nawk}
unset AWK

BUILD_MAKEFILE=${MAKEFILE:-Makefile}
unset MAKEFILE

GENERATED_BY_MESSAGE="generated by ${0##*/} and $@"

export \
    BUILD_AWK \
    BUILD_MAKEFILE \
    GENERATED_BY_MESSAGE

outdir=${BUILD_MAKEFILE%/*}
test -d "${outdir}" || mkdir -p "${outdir}"

awk_script=${thisdir}/gen-Makefile.awk
test -f "${awk_script}" || die 1 "error: awk script not found: \"${awk_script}\""
${BUILD_AWK} -f "${awk_script}" "$@" > "${BUILD_MAKEFILE}.tmp"
mv -f "${BUILD_MAKEFILE}.tmp" "${BUILD_MAKEFILE}"

echo "all done for \"${0##*/}\""
